quarkus.datasource.db-kind=h2
quarkus.datasource.jdbc.url=${db_url}
quarkus.datasource.username=${db_username}
quarkus.hibernate-orm.database.generation=drop-and-create

quarkus.smallrye-openapi.info-title=Fee Service
quarkus.smallrye-openapi.info-version=1.0.1
quarkus.smallrye-openapi.info-description=Service for fee creation

query.batch.size=${query_batch_size}
%dev.query.batch.size=10
%test.query.batch.size=10

quarkus.security.users.embedded.enabled=true
quarkus.security.users.embedded.plain-text=true
quarkus.security.users.embedded.users.jaro=pass
quarkus.security.users.embedded.roles.jaro=user,admin

quarkus.kubernetes.service-type=node-port
quarkus.kubernetes.node-port=31122
quarkus.kubernetes.image-pull-policy=never
quarkus.container-image.group=fmfi
quarkus.container-image.name=fee-service

quarkus.kubernetes.env.configmaps=app-configmap