quarkus.datasource.db-kind=h2
quarkus.datasource.jdbc.url=${db_url}
quarkus.datasource.username=${db_username}
quarkus.hibernate-orm.database.generation=drop-and-create

quarkus.smallrye-openapi.info-title=Fee Service
quarkus.smallrye-openapi.info-version=1.0.1
quarkus.smallrye-openapi.info-description=Service for fee creation

query.batch.size=${query_batch_size}
%dev.query.batch.size=10
%test.query.batch.size=10

quarkus.security.users.embedded.enabled=true
quarkus.security.users.embedded.plain-text=true
quarkus.security.users.embedded.users.jaro=${user_password}
quarkus.security.users.embedded.roles.jaro=user,admin

quarkus.container-image.group=fmfi
quarkus.container-image.name=fee-service

quarkus.kubernetes.image-pull-policy=never
quarkus.kubernetes.service-type=load-balancer
quarkus.kubernetes.ports."http".host-port=8080

quarkus.kubernetes.namespace=default
quarkus.kubernetes-client.trust-certs=true
quarkus.kubernetes-client.master-url=https://kubernetes.docker.internal:6443
quarkus.kubernetes-client.client-cert-data=${CLIENT_CERT_DATA}
quarkus.kubernetes-client.client-key-data=${CLIENT_CERT_KEY}

quarkus.kubernetes.env.configmaps=app-configmap
quarkus.kubernetes.env.secrets=app-secret