quarkus.datasource.db-kind=h2
quarkus.datasource.jdbc.url=jdbc:h2:mem:test
quarkus.hibernate-orm.database.generation=drop-and-create

quarkus.smallrye-openapi.info-title=Fee Service
quarkus.smallrye-openapi.info-version=1.0.1
quarkus.smallrye-openapi.info-description=Service for fee creation

query.batch.size=${QUERY_BATCH_SIZE}
%dev.query.batch.size=10
%test.query.batch.size=10